package com.aiphotostudio.bgremover

/**
 * This file was accidentally created and contained a redeclaration of AIApplication.
 * BuildConfig is automatically generated by Gradle when 'buildConfig = true' is set in build.gradle.kts.
 */
